name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g firebase-tools
      - run: npm ci
      - run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
